/** Audit event codes in words. The code stays visible as secondary text, so nothing is hidden. */
export const AUDIT_LABELS: Record<string, string> = {
  "owner.signed_in": "Owner signed in",
  "program.created": "Program created",
  "program.published": "Program published",
  "program.paused": "Joining paused",
  "program.marked_demo": "Marked as demo",
  "program.schedule_updated": "Round schedule changed",
  "vault.deployed": "Vault deployed",
  "vault.deposit": "Vault funded",
  "vault.limits_updated": "Vault limits changed",
  "vault.withdrawn": "Funds withdrawn",
  "vault.paused": "Vault paused",
  "vault.unpaused": "Vault resumed",
  "contributor.signed_in_x": "Contributor signed in with X",
  "contributor.joined": "Contributor joined",
  "contributor.wallet_verified": "Payout wallet verified",
  "contributor.wallet_changed": "Payout wallet changed",
  "contributor.github_set": "GitHub username set",
  "contributor.github_connected": "GitHub connected",
  "submission.created": "Work submitted",
  "decision.recorded": "Agent decided",
  "decision.override_requested": "Review decision sent",
  "decision.overridden": "Decision changed by reviewer",
  "decision.payout_recheck_failed": "Rejected at payout re-check",
  "payee.registered": "Payout wallet registered in vault",
  "payee.changed": "Payout wallet updated in vault",
  "round.started_early": "Round started early",
  "round.close_requested": "Round close requested",
  "round.closed": "Round closed",
  "round.planned": "Payouts planned",
  "round.proposed": "Round proposed on Arc",
  "round.awaiting_approval": "Waiting for owner approval",
  "round.approved": "Round approved",
  "round.executed": "Round paid",
  "round.nothing_to_pay": "Round closed with nothing to pay",
  "round.failed": "Round failed",
  "payout.executed": "Payout sent",
};

export const auditLabel = (action: string) =>
  AUDIT_LABELS[action] ?? action.replace(/[._]/g, " ").replace(/^\w/, (c) => c.toUpperCase());
